# Configuration file for coupled_rrt planner

goal_threshold: 1.0 # Distance threshold to consider goal reached
goal_bias: 0.1 # Probability of sampling the goal during RRT expansion
timelimit: 600
cbs_timeout: 1.0
check_transition_feasibility: true
transition_feasibility_robot_size_multiplier: 1.2
max_obstacle_volume_percent: 0.5
max_refinement_levels: 2